# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G -Darchitectury.loom.disableModRemapVersionCheck=true -Dfabric.loom.disableModRemapVersionCheck=true
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.20.1
curseforge_minecraft_version=1.20.1
loader_version=0.16.10

# Mod Properties
mod_version=4.1.1+1.20.1-VanillaBackport
maven_group=me.drex.instantfeedback
archives_base_name=instantfeedback


# Dependencies
fabric_version=0.92.11+1.20.1
vanillabackport_version=KbcStX3T
platform_version=kM9ocKlu

architectury.loom.disableModRemapVersionCheck=true
fabric.loom.disableModRemapVersionCheck=true